AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'

Metrics/BlockLength:
  Max: 50

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Naming/FileName:
  Exclude:
    - 'Gemfile'

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
