version: '3'

services:
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - /data/block-log-api/postgresql/data/:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    links:
      - api

  api:
    build: .
    env_file:
      - .env
    links:
      - postgres
    volumes:
      - ./config/master.key:/var/www/block-log-api/config/master.key:ro
      - /data/block-log-api/log/:/var/www/block-log-api/log/
