default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

local_connection: &local_connection
  host: <%= ENV.fetch('DATABASE_HOST') { '0.0.0.0' } %>
  port: 5432
  username: <%= ENV.fetch('DATABASE_USER') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>

development:
  <<: *default
  <<: *local_connection
  database: block-log-api_development

test:
  <<: *default
  <<: *local_connection
  database: block-log-api_test

production:
  <<: *default
  database: block-log-api_production
  url: <%= ENV['DATABASE_URL'] %>
